# Generated by Django 2.2.28 on 2023-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230530_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_case',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
